### ISSUE TITLE
HTTP status 500 - Internal server error

### ISSUE THREAD

**Issue by mohbilly** [zwindler/docker-xwiki#3]
I tried running the kubernetes files, it works fine however there is an Internal server error 500 when I tried accessing the web application. I adjusted the hibernate.cfg.xml with and it still didn't work. Any idea what's wrong?

**Comment by zwindler** [comment]
Hi !
Any reason why you don't use official XWiki docker image ?
I did this image when there was no official image. Since then they released one (I even helped a little to clean up the first attempts, but now it's fairly stable).
