### ISSUE TITLE
Need to update installer

### ISSUE THREAD

**Issue by kolob204** [zwindler/docker-xwiki#4]
![image](https://github.com/zwindler/docker-xwiki/assets/57072562/59d3100f-7f9b-444e-9a7c-3a43e5da59ff)

link http://download.forge.ow2.org/xwiki/xwiki-10.3.war - doesn't exist :-)

**Comment by zwindler** [comment]
Wow, this repository is ANCIENT 🤣

Everything in it is super outdated. I'll take a look but you should look for official alternatives (this is a non official image I made so long ago)

**Comment by zwindler** [comment]
Fixed (just for fun), but please, use official image ;)
